import { db } from '$lib/services/firebase';
import {
	collection,
	doc,
	setDoc,
	updateDoc,
	getDoc,
	getDocs,
	onSnapshot,
	query,
	where
} from 'firebase/firestore';
import type { Tournament, Match, Round, Player } from '$lib/types/firebase';

const TOURNAMENTS_COLLECTION = 'tournaments';

/**
 * Creates a new tournament via the backend API.
 * The backend handles inviteCode generation and default values.
 */
export async function createTournament(name: string, userId: string, format: 'BO1' | 'BO3'): Promise<string> {
	const tournamentRef = doc(collection(db, TOURNAMENTS_COLLECTION));
	const tournamentData: Omit<Tournament, 'id'> = {
		name,
		createdBy: userId,
		createdAt: new Date(),
		status: 'registration',
		currentRound: 0,
		totalRounds: 0,
		format,
		inviteCode: '' // Generated by backend
	};

	await setDoc(tournamentRef, tournamentData);
	return tournamentRef.id;
}

/**
 * Fetches all tournaments created by a specific judge
 */
export async function getTournamentsByJudge(userId: string): Promise<Tournament[]> {
	const q = query(collection(db, TOURNAMENTS_COLLECTION), where('createdBy', '==', userId));
	const querySnapshot = await getDocs(q);

	return querySnapshot.docs.map(doc => ({
		id: doc.id,
		...doc.data()
	} as Tournament));
}

/**
 * Updates tournament data
 */
export async function updateTournament(id: string, data: Partial<Tournament>): Promise<void> {
	const docRef = doc(db, TOURNAMENTS_COLLECTION, id);
	await updateDoc(docRef, data);
}

/**
 * Fetches a tournament document once
 */
export async function getTournament(id: string): Promise<Tournament | null> {
	const docRef = doc(db, TOURNAMENTS_COLLECTION, id);
	const docSnap = await getDoc(docRef);

	if (docSnap.exists()) {
		return { id, ...docSnap.data() } as Tournament;
	}
	return null;
}

/**
 * Subscribes to real-time updates of a tournament.
 * Returns an unsubscribe function to be called in onDestroy.
 */
export function subscribeToTournament(id: string, callback: (tournament: Tournament) => void) {
	const docRef = doc(db, TOURNAMENTS_COLLECTION, id);

	return onSnapshot(docRef, (snapshot) => {
		if (snapshot.exists()) {
			callback({ id, ...snapshot.data() } as Tournament);
		}
	});
}

/**
 * Fetches the rounds for a given tournament from Firestore.
 */
export async function getRounds(tournamentId: string): Promise<Round[]> {
	const roundsCol = collection(db, TOURNAMENTS_COLLECTION, tournamentId, 'rounds');
	const snapshot = await getDocs(roundsCol);
	return snapshot.docs.map(doc => ({
		id: doc.id,
		...doc.data()
	} as Round));
}

/**
 * Finds the round document for a given round number.
 */
export async function findRound(tournamentId: string, roundNumber: number): Promise<Round | null> {
	const roundsCol = collection(db, TOURNAMENTS_COLLECTION, tournamentId, 'rounds');
	const q = query(roundsCol, where('roundNumber', '==', roundNumber));
	const snapshot = await getDocs(q);
	if (snapshot.empty) return null;
	const doc = snapshot.docs[0];
	return { id: doc.id, ...doc.data() } as Round;
}

/**
 * Subscribes to real-time updates of matches for a specific round in a tournament.
 * Uses the round's Firestore document ID (not the round number).
 */
export function subscribeToMatches(tournamentId: string, roundDocId: string, callback: (matches: Match[]) => void) {
	const matchesCol = collection(db, TOURNAMENTS_COLLECTION, tournamentId, 'rounds', roundDocId, 'matches');

	return onSnapshot(matchesCol, (snapshot) => {
		const matches = snapshot.docs.map(doc => ({
			id: doc.id,
			...doc.data()
		} as Match));
		callback(matches);
	});
}

/**
 * Subscribes to real-time updates of players for a tournament.
 */
export function subscribeToPlayers(tournamentId: string, callback: (players: Player[]) => void) {
	const playersCol = collection(db, TOURNAMENTS_COLLECTION, tournamentId, 'players');

	return onSnapshot(playersCol, (snapshot) => {
		const players = snapshot.docs.map(doc => ({
			id: doc.id,
			...doc.data()
		} as Player));
		callback(players);
	});
}